### ISSUE TITLE
Add YouTube link into index page

### ISSUE THREAD

**Issue by apletnev** [odessajavaclub/odessajavaclub.github.io#26]
Add an youtube link: 
https://www.youtube.com/playlist?list=PLtF9zIdm3WWGFIeOaj8L5M_pnBz_b3Su1

into the index page, something like this:
https://github.com/lvivJavaClub/lvivJavaClub.github.io/blob/master/_layouts/default.html#L20

**Comment by apletnev** [comment]
@AlexAleksandrov kindly reminder

**Comment by msashkin** [comment]
Resolved by #28
